"""
automag.2_coll.run_enumlib
==========================

Script which runs enumlib.

.. codeauthor:: Michele Galasso <m.galasso@yandex.com>
"""

import os

from ase.io import read

ATOMIC_TYPES = 2

# location of the poscar file with the input structure
atoms = read('../input/Fe2O3-alpha.vasp')

os.mkdir('enumlib')
os.chdir('enumlib')

with open('struct_enum.in', 'w') as f:
    f.write('generated by automag\n')
    f.write('bulk\n')

    for lat_vector in atoms.get_cell():
        for component in lat_vector:
            f.write(f'{component:14.10f}        ')
        f.write('\n')

    f.write(f'  {ATOMIC_TYPES + 1} -nary case\n')
    f.write(f'    {atoms.get_number_of_atoms()} # Number of points in the multilattice\n')

    for atom in atoms:
        for component in atom.position:
            f.write(f'{component:14.10f}        ')
        if atom.symbol == 'Fe':
            f.write('0/1\n')
        else:
            f.write('2\n')

    f.write('    1 1   # Starting and ending cell sizes for search\n')
    f.write('0.10000000E-06 # Epsilon (finite precision parameter)\n')
    f.write('full list of labelings\n')
    f.write('# Concentration restrictions\n')
    f.write('6  6  30\n')
    f.write('6  6  30\n')
    f.write('18 18 30\n')

os.system('/home/michele/softs/enumlib/src/enum.x')
os.system('/home/michele/softs/enumlib/aux_src/makeStr.py 1 90')
