import os
import shutil
import subprocess


### START OF INPUT PART ###

# choose the desired mode: 'encut' or 'kgrid'
mode = "encut"

input_file_name = "pw.conv.in"

# encut values (ignored in kgrid mode)
encut_values = range(30, 80, 5)

# kpoints values (ignored in encut mode)
kpoints_values = [
    [2, 2, 2],
    [3, 3, 3],
    [4, 4, 4],
    [5, 5, 5],
    [6, 6, 6],
]

# sigma values (ignored in encut mode)
sigma_values = [0.05, 0.10, 0.15, 0.20]

# root dir for the convergence test
# encut mode: it must contain a raw_input folder with INCAR (without ENCUT), POSCAR, POTCAR, KPOINTS and jobscript.sh
# kgrid mode: it must contain a raw_input folder with INCAR (without SIGMA), POSCAR, POTCAR and jobscript.sh
calc_dir = "/public/home/ac4fa6jhhb/michele/Tb4H23/1_conv_tests/encut"

### END OF INPUT PART ###

raw_input_files = [input_file_name, "jobscript.sh"]

assert mode in ["encut", "kgrid"]
assert os.path.exists(calc_dir)
assert os.path.exists(os.path.join(calc_dir, "raw_input"))
for filename in raw_input_files:
    assert os.path.exists(os.path.join(calc_dir, "raw_input", filename))

if mode == "encut":
    for encut in encut_values:
        # clean previous run
        if os.path.exists(os.path.join(calc_dir, str(encut))):
            shutil.rmtree(os.path.join(calc_dir, str(encut)))

        os.mkdir(os.path.join(calc_dir, str(encut)))
        shutil.copy(os.path.join(calc_dir, "raw_input", "jobscript.sh"), os.path.join(calc_dir, str(encut)))

        # add encut value to input file
        with open(os.path.join(calc_dir, "raw_input", input_file_name), "r") as template_file:
            with open(os.path.join(calc_dir, str(encut), input_file_name), "w") as current_file:
                for line in template_file:
                    if "!ecutwfc" in line:
                        leading_spaces = line.split("!")[0]
                        new_line = leading_spaces + f"ecutwfc = {encut}\n"
                        current_file.write(new_line)
                    else:
                        current_file.write(line)

        os.chdir(os.path.join(calc_dir, str(encut)))
        subprocess.run(["sbatch", "jobscript.sh"])
else:
    for kpoints in kpoints_values:
        for sigma in sigma_values:
            dir_name = ''.join(str(item) for item in kpoints) + '_' + str(sigma).replace(".", "")
            # clean previous run:
            if os.path.exists(os.path.join(calc_dir, dir_name)):
                shutil.rmtree(os.path.join(calc_dir, dir_name))

            os.mkdir(os.path.join(calc_dir, dir_name))
            for filename in files_to_copy:
                shutil.copy(os.path.join(calc_dir, "raw_input", filename), os.path.join(calc_dir, dir_name))

            # append SIGMA to INCAR
            with open(os.path.join(calc_dir, dir_name, "INCAR"), "a") as f:
                f.write("\n\n# Added by Automag\n")
                f.write("SIGMA = " + str(sigma) + "\n")

            # create KPOINTS file
            with open(os.path.join(calc_dir, dir_name, "KPOINTS"), "w") as f:
                f.write("Generated by Automag\n")
                f.write("0\n")
                f.write("Gamma\n")
                f.write(f"{' '.join(str(item) for item in kpoints)}\n")

            os.chdir(os.path.join(calc_dir, dir_name))
            subprocess.run(["sbatch", "jobscript.sh"])
